---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: openfaas
    component: oidc-plugin
  name: oidc-plugin
  namespace: "openfaas"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: oidc-plugin
    spec:
      containers:
      - name:  oidc-plugin
        resources:
          requests:
            memory: "20Mi"
            cpu: "20m"
        image: alexellis/oidc-plugin-dist:0.1.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
        env:
        - name: client_id
          value: "value"
        - name: client_secret
          value: "value"
        - name: cookie_domain
          value: "value"
        - name: base_host
          value: "value"
        - name: port
          value: "8080" # leave as default
        - name: authorize_url
          value: "value"
        - name: welcome_page_url
          value: "value"
        - name: public_key_path
          value: ""  # leave blank if using jwks
        - name: audience
          value: "value"
        - name: token_url
          value: "value"
        - name: scopes
          value: "openid profile email"
        - name: jwks_url
          value: "value"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
