---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: oidc-plugin
  namespace: openfaas
spec:
  rules:
  - host: oauth.myfaas.club
    http:
      paths:
      - backend:
          serviceName: oidc-plugin
          servicePort: 8080
