---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: openfaas
    component: oidc-plugin
  name: oidc-plugin
  namespace: "openfaas"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: oidc-plugin
    spec:
      containers:
      - name:  oidc-plugin
        resources:
          requests:
            memory: "20Mi"
            cpu: "20m"
        image: alexellis/oidc-plugin-dist:0.2.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 10001
        env:
        - name: client_id
          value: "D4DJmNdogNZvCzyuNHppeOsN9foxh9Q8"
        - name: client_secret
          value: "29LKl660CCjivWXscY4Kx_S8VNQZV9zWOIocx8tKNBMOjW-Qz4UhMGtVK8tASDUP"
        - name: cookie_domain
          value: ".myfaas.club"
        - name: base_host
          value: "http://oauth.myfaas.club"
        - name: port
          value: "8080" # leave as default
        - name: authorize_url
          value: "https://alexellis.eu.auth0.com/authorize"
        - name: welcome_page_url
          value: "http://gw.myfaas.club"
        - name: public_key_path
          value: ""  # leave blank if using jwks
        - name: audience
          value: "https://alexellis.eu.auth0.com/api/v2/"
        - name: token_url
          value: "https://alexellis.eu.auth0.com/oauth/token"
        - name: scopes
          value: "openid profile email"
        - name: jwks_url
          value: "https://alexellis.eu.auth0.com/.well-known/jwks.json"
        - name: insecure_tls
          value: "false"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
